### ISSUE TITLE
RSS Feed for announcements

### ISSUE THREAD

**Issue by darkdragon-001** [openela/openela.org#11]
If you are using Hugo, you can easily configure the templates: https://gohugo.io/templates/rss/

**Comment by NeilHanlon** [comment]
Thanks for the request. This led me down a bit of a rabbit hole, but, in the end, RSS feeds _are_ currently available for our news posts: https://openela.org/news/index.xml

**Comment by darkdragon-001** [comment]
> Thanks for the request. This led me down a bit of a rabbit hole, but, in the end, RSS feeds _are_ currently available for our news posts: https://openela.org/news/index.xml

This is awesome!

In order for it to be more easily accessible by others, could you add a header like
```html
<link rel="alternate" type="application/rss+xml" title="News" href="/news/index.html"/>
```

**Comment by NeilHanlon** [comment]
> > Thanks for the request. This led me down a bit of a rabbit hole, but, in the end, RSS feeds _are_ currently available for our news posts: https://openela.org/news/index.xml
> 
> This is awesome!
> 
> In order for it to be more easily accessible by others, could you add a header like
> 
> ```
> <link rel="alternate" type="application/rss+xml" title="News" href="/news/index.html"/>
> ```

Yep! #24 addresses this, as well as simplifies how the overall `Announcements` listing works

**Comment by darkdragon-001** [comment]
Awesome, thanks!
