### ISSUE TITLE
Ask RedHat if they want to join

### ISSUE THREAD

**Issue by darkdragon-001** [openela/openela.org#13]
It might sound strange at the beginning but thinking more about this, it might be a clever resolution of the current situation benefiting everyone:
- RedHat can share the maintenance cost with others
- Free downstream distros are possible again
- Would be similar to Debian but in the rpm space, RHEL would become like Ubuntu in this analogy
- Mostly compatible with RHEL by definition

**Comment by NeilHanlon** [comment]
Everyone is welcome to join OpenELA :) 

I am going to close this issue as it is out of scope for the website repository, but please do not take this as "they're not welcome."
