### ISSUE TITLE
CI does not cover pull requests?

### ISSUE THREAD

**Issue by hartwork** [openela/openela.org#18]
Hi!

The CI at https://github.com/openela/openela.org/blob/main/.github/workflows/hugo.yaml seems to only run when (a) pushed to `master` or (b) when manually triggered but _not_ for pull requests. In that current setup, it will be possible for pull requests to break `master` and only notice that _after_ merge. Is that beneficial and intended?

Best, Sebastian

**Comment by NeilHanlon** [comment]
Definitely. We are going to be using `prow` as part of our CI for the entire organization, and this will be managed in a similar way.

Thank you for noticing and reporting this!

**Comment by hartwork** [comment]
@NeilHanlon use of prow sounds a like a bigger migration? I think before a migrating to prow all it would take if wanted would be to:
- Add [`pull_request`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) to https://github.com/openela/openela.org/blob/92fe9fde5bba04e654ac2dd269a05e05be6f558f/.github/workflows/hugo.yaml#L3
- Exclude job `deploy` from pull requests (probably by adding a [condition](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution))

Just an idea.

**Comment by NeilHanlon** [comment]
You're right. I'll get to this today :)

**Comment by hartwork** [comment]
@NeilHanlon any news?

**Comment by hartwork** [comment]
@NeilHanlon any news?

**Comment by NeilHanlon** [comment]
I've been working on some changes here but haven't had time to implement them. I'm open to help if you'd like to work on it.

**Comment by hartwork** [comment]
> I'm open to help if you'd like to work on it.

@NeilHanlon here you go: #54

**Comment by hartwork** [comment]
@NeilHanlon any thoughts on pull request #54?

**Comment by hartwork** [comment]
@NeilHanlon any thoughts on pull request #54?
