### ISSUE TITLE
Misleading promotion of non-existant (or non-public?) source location git.openela.org?

### ISSUE THREAD

**Issue by hartwork** [openela/openela.org#19]
Hi!

Both https://openela.org/ and https://github.com/openela/openela.org/blob/main/static/images/illustrations/git-forge.png advertise a GitLab instance deployed at https://git.openela.org/ (according to the browser address bar) while that URL is either not working yet or not anymore or not accessible to the public — ?

As the maintainer of Expat I was looking to find the Git repository that packages Expat for OpenELA and I did find https://github.com/openela-main/expat eventually but not through any of the OpenELA documentation or website or FAQ but through Google and news articles. Is that intended?

Please link to https://github.com/openela-main more visibly and fix the `git.openela.org` situation some way please. Thank you! :pray: 

Best, Sebastian

**Comment by NeilHanlon** [comment]
We've changed up the misleading screenshot, and have also added a link to the openela-main organization right from the main navigation bar.

Thank you for your report and for your work maintaining libexpat!

**Comment by hartwork** [comment]
@NeilHanlon thanks for the adjustments, way better now!

For anyone else curious, the related commits are:
- 155408c10289bc5a81b09fe901f29be37dd31fe8
- 81eb8cad72ec8ab25251bcf29de0eadc669c1bbc
